setopt autocd       # auto cd when given a dir name
setopt extendedglob # expand #, ~, and ^
# setopt menucomplete # use fist completion on tab, then cycle
setopt nomatch      # print errors when using invalid filename expansion

zle_highlight=('paste:none')

# Useful Functions
source "$ZDOTDIR/zsh-functions"

# Normal files to source
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-exports"
zsh_add_file "zsh-path"
zsh_add_file "zsh-prompt"

# Plugins
zsh_add_plugin "jeffreytse/zsh-vi-mode"
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins

# Append a command directly
zvm_after_init_commands+=('[ -f "$ZDOTDIR/zsh-fzf" ] && source "$ZDOTDIR/zsh-fzf"')
