setopt autocd       # auto cd when given a dir name
setopt extendedglob # expand #, ~, and ^
# setopt menucomplete # use fist completion on tab, then cycle
setopt nomatch      # print errors when using invalid filename expansion

zle_highlight=('paste:none')

# Useful Functions
source "$ZDOTDIR/zsh-functions"

# Normal files to source
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-completion"
zsh_add_file "zsh-exports"
zsh_add_file "zsh-path"
zsh_add_file "zsh-prompt"

# Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins

# Enable FZF key bindings
zsh_add_file "zsh-fzf"

# Enable Homebrew
eval $(/opt/homebrew/bin/brew shellenv)

# Use starship prompt
eval "$(starship init zsh)"

# Enable NVM
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads NVM
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# Enable GHCup
[ -f "/home/james/.ghcup/env" ] && source "/home/james/.ghcup/env" # ghcup-env

# Enable zoxide
eval "$(zoxide init zsh)"

# Enable thefuck
eval $(thefuck --alias ugh)

# Ename granted / assume
alias assume="source assume"
